=== tlaabs/Web-Programming/2Week/bulletin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3schools.com"
	xmlns="http://www.w3schools.com" elementFormDefault="qualified">
	
	<xs:element name="BOARD" type="BOARDTYPE" />

	<xs:complexType name="BOARDTYPE">
		<xs:sequence>
			<xs:element name="ARTICLE" type="ARTICLETYPE" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ARTICLETYPE">
		<xs:sequence>
			<xs:element name="TITLE" type="xs:string"></xs:element>
			<xs:element name="MESSAGE" type="xs:string"></xs:element>
			<xs:element name="ID" type="xs:string"></xs:element>
			<xs:element name="NAME" type="xs:string"></xs:element>
			<xs:element name="REPLY" type="REPLYTYPE" minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="REPLYTYPE">
		<xs:sequence>
			<xs:element name="MESSAGE" type="xs:string"></xs:element>
			<xs:element name="ID" type="xs:string"></xs:element>
			<xs:element name="NAME" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== tlaabs/Web-Programming/2Week/bulletin.xml
<?xml version="1.0" encoding="UTF-8"?>
<BOARD xmlns="http://www.w3schools.com" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.w3schools.com bulletin.xsd">
	<ARTICLE>
		<TITLE>TODAY IS ....</TITLE>
		<MESSAGE>GOGO</MESSAGE>
		<ID>DEVSIM</ID>
		<NAME>SIMSEYONG</NAME>
		<REPLY>
			<MESSAGE>GOOD</MESSAGE>
			<ID>TLATPDYD</ID>
			<NAME>YONG2</NAME>
		</REPLY>
	</ARTICLE>

	<ARTICLE>
		<TITLE>TODAY IS ....</TITLE>
		<MESSAGE>GOGO</MESSAGE>
		<ID>DEVSIM</ID>
		<NAME>SIMSEYONG</NAME>
	</ARTICLE>

</BOARD>
